### ISSUE TITLE
[BE] 서버에서 웹팩 빌드 시도

### ISSUE THREAD

**Issue by beginin15** [codesquad-member-2020/dust-1#73]
- 프론트에서 빌드해주신 파일을 scp 하는 것이 번거로운 것 같아서 서버에서 직접 빌드해보려고 합니다.
- 오늘안에 실패하면 그냥 포기하려고 합니다. (ㅎㅎ)

**Comment by sungik-choi** [comment]
편하게 하셔도 돼요!

**Comment by beginin15** [comment]
- npm run build 시 오류가 발생함
- package.json 파일에 명세되어 있는 의존성 라이브러리를 npm install 해주고 나니 빌드 성공함 (맞는 방법?)
---
- npx build 시에는 여전히 안되는건 잘 모르겠음

**Comment by ksundong** [comment]
빌드가 된건가요? 제대로 된 거 아니면 이슈 살려두시는게 좋을 것 같네요

**Comment by ksundong** [comment]
npm 은 처음받으면 npm -i가 국룰입니다.

**Comment by ksundong** [comment]
그리고 오류가 발생함이라고 쓰시면 이슈를 혼자만 해결하겠다는 의미라고 생각되네요.
오류가 발생한다면 어떤 오류가 발생하는지, 어디까지 찾아봤는지는 알려주는 것이 좋을 것 같네요.

약간 쓴소리긴 한데, 적어도 개발자라면, 오류가 발생합니다. 보다는 이런 오류가 발생합니다. 가 맞을 것 같아요.
슬랙방에도 로컬에서 하니까 오류가 나네요. 라고 주셨는데, 저는 저 메시지만 가지고 얻을 수 있는 단서가 하나도 없어서 직접 테스트해봐야 합니다 ㅠㅠ
